### ISSUE TITLE
Error about style ?

### ISSUE THREAD

**Issue by automateyournetwork** [gera2ld/markmap-lib#12]
Hello - I apologize if I am doing something wrong or have missed a step but I get an error when I run the command:

 markmap CORE.md
/usr/lib/node_modules/markmap-lib/dist/index.js:39
        style = { ...style,
                  ^^^

SyntaxError: Unexpected token ...
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:549:28)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/lib/node_modules/markmap-lib/bin/cli.js:4:27)

Have I missed something?

**Comment by automateyournetwork** [comment]
I had to refresh node.js thanks its working
