### ISSUE TITLE
i got a type error after using the markmap node.md command

### ISSUE THREAD

**Issue by CMW845751770** [gera2ld/markmap-lib#17]
that is the result after i typing markmap test.md and i am sure that the md file is correct.
`(node:528) UnhandledPromiseRejectionWarning: TypeError: processors is not iterable
    at getParams (C:\Users\cmw天下第一\AppData\Roaming\npm\node_modules\markmap-lib\dist\template.js:37:23)
    at C:\Users\cmw天下第一\AppData\Roaming\npm\node_modules\markmap-lib\dist\util\loader.js:130:116
    at Array.map (<anonymous>)
    at persistJS (C:\Users\cmw天下第一\AppData\Roaming\npm\node_modules\markmap-lib\dist\util\loader.js:122:16)
    at fillTemplate (C:\Users\cmw天下第一\AppData\Roaming\npm\node_modules\markmap-lib\dist\template.js:24:79)
    at createMarkmap (C:\Users\cmw天下第一\AppData\Roaming\npm\node_modules\markmap-lib\dist\index.js:38:43)
(node:528) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:528) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

**Comment by gera2ld** [comment]
fixed in v0.7.4
