### ISSUE TITLE
Error when running watch mode

### ISSUE THREAD

**Issue by sgalla1** [gera2ld/markmap-lib#41]
When running `markmap -w <input>` I get the following error:

```
internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module 'chokidar'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/Users/galstep/.nvm/versions/node/v10.21.0/lib/node_modules/markmap-lib/dist/dev-server.js:20:40)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
```

Markmap installed as global npm module

**Comment by sgalla1** [comment]
Solved by installing [chokidar](https://github.com/paulmillr/chokidar)

Should this be added to dependencies? Or added to the readme section on Watch mode as a note?

**Comment by gera2ld** [comment]
> Should this be added to dependencies? Or added to the readme section on Watch mode as a note?

Absolutely. My fault.
